// <auto-generated />
using System;
using System.Collections.Generic;
using AiPlanner.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261009210112_ItemsTable")]
    partial class ItemsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiPlanner.Domain.Entities.AIExtraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RawInputText")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("RawResponseJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("TranscriptId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TranscriptId")
                        .IsUnique();

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("AIExtractions", (string)null);
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.AIExtractionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("AddedAudioKeys")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("AddedRecording")
                        .HasColumnType("boolean");

                    b.Property<string>("AddedText")
                        .HasMaxLength(12000)
                        .HasColumnType("character varying(12000)");

                    b.Property<bool>("AddsToCurrent")
                        .HasColumnType("boolean");

                    b.Property<Guid>("AiExtractionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Clarification")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ContinuesItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContinuesItemType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("DueDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasTime")
                        .HasColumnType("boolean");

                    b.Property<bool>("HeldByEditForm")
                        .HasColumnType("boolean");

                    b.Property<int>("Intent")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("ProposedTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("RecurrenceDays")
                        .HasColumnType("integer");

                    b.Property<int?>("RecurrenceFrequency")
                        .HasColumnType("integer");

                    b.Property<int>("RecurrenceInterval")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ResultingAppointmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResultingNoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResultingTaskItemId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SourceText")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Unrelated")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AiExtractionId", "Status");

                    b.ToTable("AIExtractionItems", (string)null);
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.AppointmentParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("AppointmentParticipants", (string)null);
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.AppointmentTag", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("AppointmentId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("AppointmentTags", (string)null);
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DescribeAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DescribedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ItemType", "ItemId");

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.ItemBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Kind");

                    b.ToTable("Items", (string)null);

                    b.HasDiscriminator<int>("Kind");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.NoteTag", b =>
                {
                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("NoteId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("NoteTags", (string)null);
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("NoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReminderId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime>("ScheduledForUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SnoozedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TaskItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("NoteId");

                    b.HasIndex("ReminderId");

                    b.HasIndex("TaskItemId");

                    b.HasIndex("UserId", "Status", "ScheduledForUtc");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.RecurrenceRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ByDay")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ByMonthDay")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomRuleExpression")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("EndsOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<int>("Interval")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxOccurrences")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RecurrenceRules", (string)null);
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int?>("MinutesBefore")
                        .HasColumnType("integer");

                    b.Property<Guid?>("NoteId")
                        .HasColumnType("uuid");

                    b.Property<bool>("PausedWithItem")
                        .HasColumnType("boolean");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("TaskItemId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("TimeOfDay")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("TriggerAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("NoteId");

                    b.HasIndex("TaskItemId");

                    b.HasIndex("UserId", "TriggerAtUtc");

                    b.ToTable("Reminders", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reminders_ExactlyOneParent", "num_nonnulls(\"TaskItemId\", \"AppointmentId\", \"NoteId\") = 1");
                        });
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.TaskTag", b =>
                {
                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("TaskItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TaskTags", (string)null);
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.Transcript", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VoiceCaptureId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VoiceCaptureId")
                        .IsUnique();

                    b.ToTable("Transcripts", (string)null);
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AiProcessingEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AiReadsMedia")
                        .HasColumnType("boolean");

                    b.Property<bool>("AppointmentRemindersEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutomaticProcessing")
                        .HasColumnType("boolean");

                    b.Property<bool>("DailySummaryEnabled")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("DailySummaryTime")
                        .HasColumnType("interval");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("DefaultReminderMinutesBefore")
                        .HasColumnType("integer");

                    b.Property<string>("FirstDayOfWeek")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("KeepRecordings")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("OneEntryPerMessage")
                        .HasColumnType("boolean");

                    b.Property<bool>("RetainAudioAfterTranscription")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReviewBeforeSave")
                        .HasColumnType("boolean");

                    b.Property<string>("Skin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("TaskRemindersEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TimeFormat")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("TranscriptRetentionDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Wallpaper")
                        .HasColumnType("boolean");

                    b.Property<string>("WallpaperPhotoKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings", (string)null);
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.VoiceCapture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("AudioStorageKeys")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("VoiceCaptures", (string)null);
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.Appointment", b =>
                {
                    b.HasBaseType("AiPlanner.Domain.Entities.ItemBase");

                    b.Property<string>("AiSummary")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("AiSummary");

                    b.Property<string>("Description")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("Text");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("Location");

                    b.Property<string>("Notes")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("Notes");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("Priority");

                    b.Property<Guid?>("RecurrenceRuleId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid")
                        .HasColumnName("RecurrenceRuleId");

                    b.PrimitiveCollection<List<DateTime>>("SkippedOccurrencesUtc")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone[]");

                    b.Property<Guid?>("SourceAiExtractionId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid")
                        .HasColumnName("SourceAiExtractionId");

                    b.Property<DateTime>("StartUtc")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateUtc");

                    b.Property<int>("Status")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("Title");

                    b.HasIndex("RecurrenceRuleId");

                    b.HasIndex("SourceAiExtractionId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.Note", b =>
                {
                    b.HasBaseType("AiPlanner.Domain.Entities.ItemBase");

                    b.Property<string>("AiSummary")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("AiSummary");

                    b.Property<string>("Content")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("Text");

                    b.Property<string>("Location")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("Location");

                    b.PrimitiveCollection<List<string>>("People")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text[]")
                        .HasColumnName("People");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("Priority");

                    b.Property<Guid?>("SourceAiExtractionId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid")
                        .HasColumnName("SourceAiExtractionId");

                    b.Property<string>("Title")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("Title");

                    b.HasIndex("SourceAiExtractionId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.TaskItem", b =>
                {
                    b.HasBaseType("AiPlanner.Domain.Entities.ItemBase");

                    b.Property<string>("AiSummary")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("AiSummary");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("Text");

                    b.Property<DateTime?>("DueDateUtc")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateUtc");

                    b.Property<bool>("HasDueTime")
                        .HasColumnType("boolean")
                        .HasColumnName("HasTime");

                    b.Property<string>("Location")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("Location");

                    b.Property<string>("Notes")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("Notes");

                    b.PrimitiveCollection<List<string>>("People")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text[]")
                        .HasColumnName("People");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("Priority");

                    b.Property<Guid?>("RecurrenceRuleId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid")
                        .HasColumnName("RecurrenceRuleId");

                    b.Property<Guid?>("SourceAiExtractionId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid")
                        .HasColumnName("SourceAiExtractionId");

                    b.Property<DateTime?>("StartDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("Title");

                    b.HasIndex("RecurrenceRuleId");

                    b.HasIndex("SourceAiExtractionId");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.AIExtraction", b =>
                {
                    b.HasOne("AiPlanner.Domain.Entities.Transcript", "Transcript")
                        .WithOne("AiExtraction")
                        .HasForeignKey("AiPlanner.Domain.Entities.AIExtraction", "TranscriptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Transcript");
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.AIExtractionItem", b =>
                {
                    b.HasOne("AiPlanner.Domain.Entities.AIExtraction", "AiExtraction")
                        .WithMany("Items")
                        .HasForeignKey("AiExtractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("AiPlanner.Domain.Entities.ProposedReminder", "ProposedReminders", b1 =>
                        {
                            b1.Property<Guid>("AIExtractionItemId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<DateTime?>("AtUtc");

                            b1.Property<int>("DaysOfWeek");

                            b1.Property<int>("Kind");

                            b1.Property<int?>("MinutesBefore");

                            b1.Property<TimeOnly?>("TimeOfDay");

                            b1.HasKey("AIExtractionItemId", "__synthesizedOrdinal");

                            b1.ToTable("AIExtractionItems");

                            b1
                                .ToJson("ProposedReminders")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AIExtractionItemId");
                        });

                    b.Navigation("AiExtraction");

                    b.Navigation("ProposedReminders");
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.AppointmentParticipant", b =>
                {
                    b.HasOne("AiPlanner.Domain.Entities.Appointment", "Appointment")
                        .WithMany("Participants")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.AppointmentTag", b =>
                {
                    b.HasOne("AiPlanner.Domain.Entities.Appointment", "Appointment")
                        .WithMany("AppointmentTags")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiPlanner.Domain.Entities.Tag", "Tag")
                        .WithMany("AppointmentTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.NoteTag", b =>
                {
                    b.HasOne("AiPlanner.Domain.Entities.Note", "Note")
                        .WithMany("NoteTags")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiPlanner.Domain.Entities.Tag", "Tag")
                        .WithMany("NoteTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.Notification", b =>
                {
                    b.HasOne("AiPlanner.Domain.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId");

                    b.HasOne("AiPlanner.Domain.Entities.Note", "Note")
                        .WithMany()
                        .HasForeignKey("NoteId");

                    b.HasOne("AiPlanner.Domain.Entities.Reminder", "Reminder")
                        .WithMany()
                        .HasForeignKey("ReminderId");

                    b.HasOne("AiPlanner.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany()
                        .HasForeignKey("TaskItemId");

                    b.Navigation("Appointment");

                    b.Navigation("Note");

                    b.Navigation("Reminder");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("AiPlanner.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.Reminder", b =>
                {
                    b.HasOne("AiPlanner.Domain.Entities.Appointment", "Appointment")
                        .WithMany("Reminders")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AiPlanner.Domain.Entities.Note", "Note")
                        .WithMany("Reminders")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AiPlanner.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany("Reminders")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Appointment");

                    b.Navigation("Note");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.TaskTag", b =>
                {
                    b.HasOne("AiPlanner.Domain.Entities.Tag", "Tag")
                        .WithMany("TaskTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiPlanner.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany("TaskTags")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.Transcript", b =>
                {
                    b.HasOne("AiPlanner.Domain.Entities.VoiceCapture", "VoiceCapture")
                        .WithOne("Transcript")
                        .HasForeignKey("AiPlanner.Domain.Entities.Transcript", "VoiceCaptureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VoiceCapture");
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("AiPlanner.Domain.Entities.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("AiPlanner.Domain.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("AiPlanner.Domain.Entities.RecurrenceRule", "RecurrenceRule")
                        .WithMany()
                        .HasForeignKey("RecurrenceRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AiPlanner.Domain.Entities.AIExtraction", "SourceAiExtraction")
                        .WithMany()
                        .HasForeignKey("SourceAiExtractionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RecurrenceRule");

                    b.Navigation("SourceAiExtraction");
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.Note", b =>
                {
                    b.HasOne("AiPlanner.Domain.Entities.AIExtraction", "SourceAiExtraction")
                        .WithMany()
                        .HasForeignKey("SourceAiExtractionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceAiExtraction");
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("AiPlanner.Domain.Entities.RecurrenceRule", "RecurrenceRule")
                        .WithMany()
                        .HasForeignKey("RecurrenceRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AiPlanner.Domain.Entities.AIExtraction", "SourceAiExtraction")
                        .WithMany()
                        .HasForeignKey("SourceAiExtractionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RecurrenceRule");

                    b.Navigation("SourceAiExtraction");
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.AIExtraction", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.Tag", b =>
                {
                    b.Navigation("AppointmentTags");

                    b.Navigation("NoteTags");

                    b.Navigation("TaskTags");
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.Transcript", b =>
                {
                    b.Navigation("AiExtraction");
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.VoiceCapture", b =>
                {
                    b.Navigation("Transcript");
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("AppointmentTags");

                    b.Navigation("Participants");

                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.Note", b =>
                {
                    b.Navigation("NoteTags");

                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("AiPlanner.Domain.Entities.TaskItem", b =>
                {
                    b.Navigation("Reminders");

                    b.Navigation("TaskTags");
                });
#pragma warning restore 612, 618
        }
    }
}
